// src/app/layout.tsx
import AuthProvider from "@/components/AuthProvider";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rail Madad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
          <div id="modal-root"></div> {/* This is the root for modals */}
        </AuthProvider>
      </body>
    </html>
  );
}
